language: cpp
stages:
  - build1
  - build2
jobs:
  include:
  - stage: build1
    os: osx
    osx_image: xcode10.2
#    env:
#    - GEOSX_TPL_DIR=/Users/travis/build/GEOSX/thirdPartyLibs/install-default-release
    before_script:
    - brew install openmpi > /dev/null 2>&1
    - brew install git-lfs > /dev/null 2>&1
#    - brew install gdrive
    - git lfs install
    - git lfs pull
#    - sudo mkdir ~/.gdrive
#    - sudo wget -O ~/.gdrive/token_v2.json https://www.dropbox.com/s/72lwwyivpzkocww/token_v2.json

    script: 
    - python ${TRAVIS_BUILD_DIR}/scripts/config-build.py -hc ${TRAVIS_BUILD_DIR}/host-configs/darwin-clang.cmake -bt Release -DNUM_PROC=2 -DENABLE_CALIPER:BOOL=OFF
    - cd build-darwin-clang-release
    - make hdf5 conduit axom silo chai raja fparser mathpresso pugixml metis parmetis superlu_dist hypre uncrustify
#    - cd ..
#    - tar -cvf install-darwin-clang-release.tar install-darwin-clang-release
#    - gdrive upload install-darwin-clang-release.tar

  - stage: build2
    os: osx
    osx_image: xcode10.2
    env:
    - GEOSX_TPL_DIR=/Users/travis/build/GEOSX/thirdPartyLibs/install-default-release
    before_script:
    - brew install openmpi > /dev/null 2>&1
    - brew install git-lfs > /dev/null 2>&1
#    - brew install gdrive
    - git lfs install
    - git lfs pull
#    - sudo mkdir ~/.gdrive
#    - sudo wget -O ~/.gdrive/token_v2.json https://www.dropbox.com/s/72lwwyivpzkocww/token_v2.json

    script: 
    - python ${TRAVIS_BUILD_DIR}/scripts/config-build.py -hc ${TRAVIS_BUILD_DIR}/host-configs/darwin-clang.cmake -bt Release -DNUM_PROC=3
#    - gdrive download install-darwin-clang-release.tar
#    - tar -xvf install-darwin-clang-release.tar
#    - rm install-darwin-clang-release.tar
    - cd build-darwin-clang-release
    - make trilinos
    - cd ..
#    - tar -cvf install-darwin-clang-release.tar install-darwin-clang-release
#    - gdrive upload install-darwin-clang-release.tar

  - stage: build1
    os: linux
    dist: trusty
    services: docker
    sudo: required
    compiler: clang6-LC-toss3
    env:
    - IMG=clang6-LC-toss3
    - GEOSX_TPL_DIR=/home/geosx/thirdPartyLibs/install-default-release
    script: 
    - echo HELLO
    
  - stage: build2
    os: linux
    dist: trusty
    services: docker
    sudo: required
    compiler: clang6-LC-toss3
    env:
    - IMG=clang6-LC-toss3
    - GEOSX_TPL_DIR=/home/geosx/thirdPartyLibs/install-default-release
    script: 
    - echo HELLO2
    
