language: cpp
stages:
  - build1
jobs:
  include:
  - stage: build1
    os: osx
    osx_image: xcode10.2
    before_script:
    - brew install openmpi > /dev/null 2>&1
    - brew install git-lfs > /dev/null 2>&1
    - git lfs install
    - git lfs pull
    script: 
    - python ${TRAVIS_BUILD_DIR}/scripts/config-build.py -hc ${TRAVIS_BUILD_DIR}/host-configs/darwin-clang.cmake -bt Release -DNUM_PROC=2 -DENABLE_CALIPER:BOOL=OFF
    - cd build-darwin-clang-release
    - make hdf5 conduit axom silo chai raja fparser mathpresso pugixml metis parmetis superlu_dist hypre uncrustify

  - stage: build1
    os: linux
    dist: trusty
    services: docker
    sudo: required
    compiler: clang6-LC-toss3
    env:
    - IMG=clang6-LC-toss3
    - GEOSX_TPL_DIR=/home/geosx/thirdPartyLibs/install-default-release
    script: 
    - cd docker
    - cp buildtpl.sh gcc8-ubuntu18
    - docker build --tag geosx/compiler:gcc8-ubuntu18 gcc8-ubuntu18
    - docker run -v ${TRAVIS_BUILD_DIR}:/home/geosx/thirdPartyLibs_repo  geosx/compiler:gcc8-ubuntu18 /home/geosx/buildtpl.sh
    
